apiVersion: v1
kind: ConfigMap
metadata:
  name: pal-tracker
  labels:
    app: pal-tracker
data:
  welcome.message: "hello from kubernetes"
  management.endpoints.web.exposure.include: "*"
  management.endpoint.health.showdetails: always
